<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Email' => 'Электронная почта',
    'First Name' => 'Имя',
    'Last Name' => 'Фамилия',
    'Name' => 'Наименование',
    'Password' => 'Пароль',
    'Password Repeat' => 'Повторите пароль',
    'Remember Me' => 'Запомнить меня',
    'Reset' => 'Сброс',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'UserName' => 'Логин',
    'Achievement Empls' => 'Достижения сотрудников',
    'Achievement Idachievement' => '',
    'Achievements' => 'Достижения',
    'Add Questionary Eml' => '',
    'Answertoquestion' => '',
    'Are you sure you want to delete this item?' => '',
    'Choose Achievement' => 'Выбрать достижение',
    'Choose Date Add' => '',
    'Create Achievement' => 'Добавить достижение',
    'Create Achievement Empl' => 'Записать достижения сотрудника',
    'Create Motivation Empl' => 'Записать средство мотивации для сотрудника',
    'Create Motivation Means' => 'Добавить средство мотивации',
    'Create Question' => '',
    'Create Question Eml' => '',
    'Created At' => 'Дата создания',
    'Date Add' => 'Дата добавления',
    'Date Up' => 'Дата обновления',
    'ID' => '',
    'Idachievement' => '',
    'Idachievement Empl' => '',
    'Idmotivation Means' => '',
    'Idquestion' => '',
    'Idquestionary Eml' => '',
    'Motivation Empls' => 'Мотивация сотруников',
    'Motivation Means' => 'Средство мотивации',
    'Motivation Means Idmotivation Means' => '',
    'Motivation Means Name' => 'Наименование средства мотивации',
    'Question' => 'Вопрос',
    'Question Emls' => '',
    'Question Idquestion' => '',
    'Questions' => 'Вопросы',
    'The requested page does not exist.' => '',
    'Update Achievement Empl: {name}' => '',
    'Update Achievement: {name}' => '',
    'Update Motivation Empl: {name}' => '',
    'Update Motivation Means: {name}' => '',
    'Update Question Eml: {name}' => '',
    'Update Question: {name}' => '',
    'Updated At' => '',
    'User ID' => '',
    'Adders' => '@@Адрес@@',
    'Categories' => '@@Категории@@',
    'Category' => '@@Категория@@',
    'Categoryname' => '@@Название категории@@',
    'Content' => '@@Контент@@',
    'Course' => '@@Учебный курс@@',
    'Course ID' => '@@Курс@@',
    'Courses' => '@@Учебные курсы@@',
    'Create Category' => '@@Создать категорию@@',
    'Create Course' => '@@Создать курс@@',
    'Create Lesson' => '@@Добавить занятие@@',
    'Create News' => '@@Добавить новость@@',
    'Create Tutor' => '@@Добавить учителя@@',
    'Date' => '@@Дата@@',
    'Header' => '@@@@',
    'Lessons' => '@@Занятия@@',
    'News' => '@@Новости@@',
    'Number' => '@@Номер@@',
    'Phone' => '@@Телефон@@',
    'Select issue date ...' => '@@@@',
    'Text' => '@@Текст@@',
    'Tutor' => '@@Преподаватель@@',
    'Tutor ID' => '@@@@',
    'Tutors' => '@@Учителя@@',
    'Update Category: {name}' => '@@Обновить категорию: {name}@@',
    'Update Course: {name}' => '@@Обновить курс: {name}@@',
    'Update Lesson: {name}' => '@@@@',
    'Update News: {name}' => '@@@@',
    'Update Tutor: {name}' => '@@@@',
    'Visibility' => '@@@@',
];
